default: &default
  adapter: postgresql
  encoding: utf8
  host: <%=ENV["POSTGRES_HOST"]%>
  database: <%=ENV["POSTGRES_DATABASE"]%>
  username: <%=ENV.fetch("POSTGRES_USER") %>
  password: <%=ENV.fetch("POSTGRES_PASSWORD") %>
  port: 5432

development:
  <<: *default
  database: <%=ENV.fetch("POSTGRES_DATABASE")%>
  pool: 60

test:
  <<: *default
  database: <%=ENV.fetch("POSTGRES_DATABASE_TEST")%>
  pool: 5

staging:
  <<: *default
  pool: 20

production:
  <<: *default
  pool: 30
