default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  database: fullstack
  username: postgres

development:
  <<: *default
  database: fullstack
  pool: 60

test:
  <<: *default
  database: fullstack_test
  pool: 5

staging:
  <<: *default
  pool: 20

production:
  <<: *default
  pool: 30
